name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: Lempki/dev-standards/.github/workflows/python-ci.yml@v0.2.0
    with:
      docker: true
      forward-python-version: "3.14"
