name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: Lempki/discord-dev-standards/.github/workflows/python-ci.yml@v0.1.1
    with:
      docker: true
